# Generated by Django 5.2 on 2025-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='description',
            new_name='how_to_make',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredients',
            field=models.TextField(default='Default Ingredient'),
            preserve_default=False,
        ),
    ]
