# Generated by Django 5.2 on 2025-04-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='category',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='customer.category'),
            preserve_default=False,
        ),
    ]
